### ISSUE TITLE
Recommend changing  notation in 1-tailed, 2-tailed commentary

### ISSUE THREAD

**Issue by anonymous2020andbeyond** [learn-co-curriculum/dsc-p-values-and-null-hypothesis#1]
## Link to Canvas

https://learning.flatironschool.com/courses/6222/pages/p-values-and-the-null-hypothesis?module_item_id=529245

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ X] Instructions unclear
- [ ] Other (explain below)

### Source

```
Example One-Tail Hypothesis

 The treatment group given this weight loss drug will lose more weight on average than the control group that was given a competitor's weight loss drug

 The treatment group given this weight loss drug will not lose more weight on average than the control group that was given a competitor's weight loss drug".

<img width="703" alt="Screenshot 2023-05-15 232649" src="https://github.com/learn-co-curriculum/dsc-p-values-and-null-hypothesis/assets/44915692/bcca3136-6385-4085-b4c8-96691723e9dc">

```

### Concern

I would recommend instead of typing `mu1` and `mu2` that you use `mutreatment` and `mu control` so that its easier to discern how the inequalities should be defined

## (Optional) Proposed Solution

See comment above

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ X] Saturn Cloud from Canvas

**Comment by gadamico** [comment]
Updated
